### ISSUE TITLE
Скласти блок контактної інформації

### ISSUE THREAD

**Issue by maksym-strus** [maksym-strus/homepage#6]
Посилання на соцмережі (Facebook чи Instagram, тощо), номер телефону чи адреса електронної скриньки, тощо. Може не всі лінки в світі, а тільки ті, що дійсно доречні.

**Comment by Destrob0** [comment]
Instagram: https://www.instagram.com/?hl=uk
Facebook: https://www.facebook.com/campaign/landing.php?campaign_id=1600506868&extra_1=s%7Cc%7C303839676210%7Ce%7Cfacebook%27%7C&placement=&creative=303839676210&keyword=facebook%27&partner_id=googlesem&extra_2=campaignid%3D1600506868%26adgroupid%3D60825658456%26matchtype%3De%26network%3Dg%26source%3Dnotmobile%26search_or_content%3Ds%26device%3Dc%26devicemodel%3D%26adposition%3D%26target%3D%26targetid%3Dkwd-362360550869%26loc_physical_ms%3D1012859%26loc_interest_ms%3D%26feeditemid%3D%26param1%3D%26param2%3D&gclid=Cj0KCQjwtLT1BRD9ARIsAMH3BtWTgqZecVwzlMWjRz6SMur-IzMom-cW4ptpDLexxM6c-oL3cHTDGpAaAh6XEALw_wcB

**Comment by maksym-strus** [comment]
Дякуюю
