### ISSUE TITLE
Скласти додаткові інформаційні блоки

### ISSUE THREAD

**Issue by maksym-strus** [maksym-strus/homepage#6]
Можна зробити резюме менш формальним, додавши додаткові блоки, які містять корисну інформацію, але подають її в "розважальній" формі. Наприклад, що подобається і не подобається, сильні і слабкі сторони, перелік навиків чи хобі, інфографіка або ж інтерактивні модулі, тощо. Варто написати контент такого блоку раніше, ніж починати верстку, бо його розміри впливатимуть на розміщення елементів на сторінці.

**Comment by Destrob0** [comment]
<section>
  <h3>Languages</h3>
  <p class="tags small"><span>ENGLISH</span><span>MANDARIN</span><span>JAPANESE</span></p>
</section>
<section>
  <h3>Skills</h3>
  <p class="tags small">KARATE ENERGY ATTACK SHORYUKEN WALKING BAREFOOT PLAYING VIDEOGAMES DOING BURGERS MASHING POTATOES COPYWRITING ACTING VOICEOVERS</p>
</section>
<section>
  <h3>Character</h3>
  <p class="tags small">NOBLE DIRECT BOLD CONFIDENT DARING SCHIZOPHRENIC DRAMATIC PERSUASIVE IMMEDIATE WISE</p>
</section>
<section>
  <h3>Likes&#x1f603;</h3>
  <p class="tags small">GI VEGETABLES BLOOD SMALL MARSHMELLOWS RED COLOR KILLED ENEMY</p>
</section>
<section>
  <h3>Dislikes&#x1f61e;</h3>
  <p class="tags small">BISONS GHOSTS SMARTPHONES SMELL OF SEAFOOD BARBER SHOPS SLEEVES</p>
</section>
<section>
  <h3>Wants&#x1f97a;</h3>
  <p class="tags small bulleted">BE FIT WRITE MORE BOOKS FIND A GIRLFRIEND TO GO TO CINEMA WITH KILL ALL OF AKUMA FAMILY</p>
</section>

**Comment by maksym-strus** [comment]
Yes, it might be so meanful)
